# NumPy

In [7]:
import numpy as np

np.array([1,2,"1"])
type(np.array)

builtin_function_or_method

In [10]:
import numpy as np

classic_list = [1, 2, 3, 5, 7, 11]
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [11]:
numpy_array.shape

(6,)

In [12]:
np.array([2,4]).mean() #średnia

3.0

In [14]:
np.array([2,4]).std() #odchylenie standardowe

1.0

# Macierz

In [15]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [18]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

matrix1[0, :]

array([1, 2, 3])

In [19]:
matrix1[:, -1]

array([3, 6, 9])

# Operacje

In [21]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

matrix2.sum()

47

In [23]:
matrix2.sum(axis=0) # suma kolumn (axis=0)

array([ 2, 20, 25])

In [25]:
matrix2.sum(axis=1) # suma wierszy (axis=1)

array([ 6, 18, 23])

In [26]:
np.array([1,2]) + np.array([8,9]) # dodawanie wektorów

array([ 9, 11])

In [27]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])                # dodawanie/mnożenie macierzy

array([[ 9, 11],
       [13, 15]])

In [28]:
np.array([
	[1,2],
	[3,4]
]).dot([1,1])    # iloczyn skalarny

array([3, 7])